version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    environment:
      GCLOUD_KEYFILE: /tmp/gcloud

    steps:
      - checkout
      - setup_remote_docker

      # Install docker client
      - run:
          name: Install Docker client and dependencies
          command: |
            set -x
            VER="17.03.0-ce"
            apk add --update curl make
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # Build image and push
      - run:
          name: Build image and push
          command: |
            echo "${GOOGLE_AUTH}" | base64 -d > ${GCLOUD_KEYFILE}
            gcloud auth activate-service-account --key-file ${GCLOUD_KEYFILE}
            make container push
